### ISSUE TITLE
TO DO LIST

### ISSUE THREAD

**Issue by Yilun-Sun** [Jaden1967/APP#4]
# To-do list

- [Functional Requirements](#functional-requirements)
  * [Must include](#must-include)
  * [Map editor](#map-editor)
    + [User-driven creation of map elements](#user-driven-creation-of-map-elements)
    + [Saving a map to a text file](#saving-a-map-to-a-text-file)
    + [Loading a map from an existing map file](#loading-a-map-from-an-existing-map-file)
    + [Verification of map correctness](#verification-of-map-correctness)
- [Game Play](#game-play)
  * [Implementation](#implementation)
  * [Startup phase](#startup-phase)
  * [Reinforcement phase](#reinforcement-phase)
  * [Fortification phase](#fortification-phase)
- [Docs](#docs)
  * [Architectural design](#architectural-design)
  * [Software versioning repository](#software-versioning-repository)
  * [Javadoc API documentation](#javadoc-api-documentation)
  * [Unit testing framework](#unit-testing-framework)
  * [Coding standards](#coding-standards)

# Functional Requirements

## Must include

The game must include _==a command prompt==_ that is available throughout the usage of the game (even if you have a GUI). All the commands should be validated and give proper feedback on their effect or invalidity. Each of the commands should only work in the game phase for which they are designed for. The commands should use the exact same syntax as defined below. Some commands have options preceded by a dash. Either or both options can be used and may be used multiple times in a command. Command parameters are noted in italics.

* [ ] a command prompt

### User-driven creation of map elements

User-driven creation of map elements: country, continent, and connectivity between countries

Map editor commands:

* [x] editcontinent -add continentname continentvalue
* [x] editcontinent -remove continentname
* [x] editcountry -add countryname continentname
* [x] editcountry -remove countryname
* [x] editneighbor -add countryname neighborcountryname
* [x] editneighbor -remove countryname neighborcountryname
* [x] showmap (show all continents and countries and their neighbors)

* [x] editcountry -cood countryname (x,y)

### Saving a map to a text file

Saving a map to a text file exactly as edited (using the “domination” game map format)

Map editor command:

* [x] savemap filename

### Loading a map from an existing map file

Loading a map from an existing “domination” map file to edit or create a new map from scratch if the file does not exist

Map editor command:

* [x] editmap filename

### Verification of map correctness

Verification of map correctness. The map should be automatically validated upon loading and before saving (at least 3 types of incorrect maps). The validatemap command can be triggered anytime during map editing

Map editor command:

* [x] validatemap

# Game Play

## Implementation

Implementation of a game driver implementing and controlling the game phases according to the Risk rules.

Game play command:

* [x] showmap

(show all countries and continents, armies on each country, ownership, and connectivity)

## Startup phase

Game starts by user selection of a user-saved map file.

Startup phase command:

* [x] loadmap filename

Map is loaded as ==_a connected graph_==, which is rendered effectively to the user to enable efficient play.

User creates the players, then all countries are randomly assigned to players.

Startup phase commands:

* [x] gameplayer -add playername
* [x] gameplayer -remove playername
* [x] populatecountries

Players are allocated a number of initial armies, depending on the number of players. In round-robin fashion, the players place their given armies one by one on their own countries.

Startup phase commands:

* [x] placearmy countryname

(by each player until all players have placed all their armies) placeall (automatically randomly place all remaining unplaced armies for all players)

## Reinforcement phase

Calculation of correct number of reinforcement armies according to the Risk rules. Player place all reinforcement armies on the map. Reinforcement phase command:

* [x] reinforce countryname num

(until all reinforcements have been placed)

## Fortification phase

Implementation of a valid fortification move according to the Risk rules.

Fortification phase commands:

* [x] fortify fromcountry tocountry num
* [x] fortify none (choose to not do a move)

# Docs

## Architectural design

Short document including an architectural design diagram. Short but complete and clear description of the design, which should break down the system into cohesive modules. The architectural design should be reflected in the implementation of well-separated modules and/or folders.

## Software versioning repository

Well-populated history with dozens of commits, distributed evenly among team members, as well as evenly distributed over the time allocated to the build. A tagged version should have been created for build 1.

## Javadoc API documentation

Completed for all files, all classes and all methods.

## Unit testing framework

At least 10 relevant test cases testing the most important aspects of the code. Must include tests for: (1) map validation – map is a connected graph; (2) continent validation – continent is a connected subgraph; (3) calculation of number of reinforcement armies; (4) reading valid/invalid map files.

## Coding standards

Short and simple document describing coding standard used. Consistent and proper use of code layout, naming conventions and comments, absence of “commented out” code.

* [x] Architectural design
* [x] Software versioning repository
* [x] Javadoc API documentation
* [x] Unit testing framework
* [x] Coding standards

**Comment by Yilun-Sun** [comment]
Please carefully review this doc and pick the task that you like, and create an **_issue_** with it (don't forget to _**assign**_ yourself and people who you want to work with) @AllanInComp @KingDeath233 @Jaden1967 @Candou9
